import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'research-question',
    'courses',
    {
      type: 'category',
      label: 'For Students',
      items: [
        {
          type: 'autogenerated',
          dirName: 'students',
        },
      ],
    },
    {
      type: 'category',
      label: 'For Educators',
      items: [
        {
          type: 'autogenerated',
          dirName: 'educators',
        },
      ],
    },
    {
      type: 'category',
      label: 'For Industry',
      items: [
        {
          type: 'autogenerated',
          dirName: 'industry',
        },
      ],
    },
    {
      type: 'category',
      label: 'For Researchers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'researchers',
        },
      ],
    },
    'participant-groups',
    'timeline',
    'challenges',
    'tedx-component',
    'registration',
    'contact',
  ],
};

export default sidebars;
